import ListAllRecipe from "components/ListAllRecipe";
import Recipe from "components/Recipe";
import { Button } from "components/ui/button";
import { Input } from "components/ui/input";
import Head from "next/head";
import Link from "next/link";

function SearchBar() {

  return (
    <div className="flex flex-row p-8 mx-4">
      <Input placeholder="Search your recipes..." className="px-4 text-lg p-4" />
      <Button className="px-6 py-4 mx-4 bg-pink-50 border border-pink-200 hover:bg-pink-100 text-black outline outline-pink-100">Search </Button>
    </div>
  )
}

export default function ShowRecipe() {

  // <div className="bg-[url('https://hips.hearstapps.com/hmg-prod/images/20191011-creamy-tuscan-chicken-delish-ehg-2518-1571259200.jpg')] bg-no-repeat bg-cover h-screen bg-fixed ">
  return (
    <div className="font-poppins">
      <Head key={1}>
        <title>Ultimate Recipe App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Link href='/'>
        Back to Home
      </Link>

      <SearchBar />

      <div className="flex justify-center ">
      <Button className="p-8 text-xl text-black bg-pink-50 border border-pink-200 hover:bg-pink-100">
        Add A Recipe
      </Button>
      </div>

      <h1 className="text-3xl text-red-500 p-5">Your Recipes...</h1>
      <ListAllRecipe />
    </div>
  );
}
